# Generated by Django 4.0.6 on 2022-08-31 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CiudadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('provincia', models.CharField(default='La Pampa', max_length=255)),
                ('cp', models.PositiveSmallIntegerField()),
                ('cpa', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'ciudades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DomicilioGeoLocalizadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=255)),
                ('numero', models.PositiveSmallIntegerField()),
                ('casa', models.CharField(blank=True, max_length=50, null=True)),
                ('barrio', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('googlemaps_link', models.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.ciudadmodel')),
            ],
            options={
                'verbose_name_plural': 'Domicilios Geo Localizados',
                'ordering': ['calle'],
            },
        ),
    ]
