# Generated by Django 4.0.6 on 2022-08-31 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudadmodel',
            options={'ordering': ['nombre'], 'verbose_name': 'ciudad', 'verbose_name_plural': 'ciudades'},
        ),
        migrations.AlterModelOptions(
            name='domiciliogeolocalizadomodel',
            options={'ordering': ['calle'], 'verbose_name': 'Domicilio Geo Localizado', 'verbose_name_plural': 'Domicilios Geo Localizados'},
        ),
        migrations.AlterModelTable(
            name='ciudadmodel',
            table='gis_ciudad',
        ),
        migrations.AlterModelTable(
            name='domiciliogeolocalizadomodel',
            table='gis_domicilio_geo_localizado',
        ),
    ]
