# Generated by Django 4.0.6 on 2022-08-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0002_alter_ciudadmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domiciliogeolocalizadomodel',
            options={'ordering': ['calle'], 'verbose_name': 'Domicilio Geolocalizado', 'verbose_name_plural': 'Domicilios Geolocalizados'},
        ),
        migrations.AlterModelTable(
            name='domiciliogeolocalizadomodel',
            table='gis_domicilio_geolocalizado',
        ),
    ]
