# Generated by Django 4.0.6 on 2022-10-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0003_alter_domiciliogeolocalizadomodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domiciliogeolocalizadomodel',
            name='calle_alias',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='domiciliogeolocalizadomodel',
            name='has_alias',
            field=models.BooleanField(default=False),
        ),
    ]
