# Generated by Django 4.0.6 on 2022-10-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis', '0004_domiciliogeolocalizadomodel_calle_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domiciliogeolocalizadomodel',
            name='is_pending_alias',
            field=models.BooleanField(default=False),
        ),
    ]
