# Generated by Django 4.0.6 on 2022-08-31 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userloginmodel',
            options={'verbose_name': 'User Login', 'verbose_name_plural': 'User Logins'},
        ),
        migrations.AlterModelTable(
            name='userloginmodel',
            table='login_userlogin',
        ),
    ]
