# Generated by Django 4.0.6 on 2022-08-31 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chasis', models.CharField(max_length=50)),
                ('denominacion', models.CharField(max_length=50)),
                ('modems_online', models.PositiveSmallIntegerField()),
                ('modems_offline', models.PositiveSmallIntegerField()),
                ('modems_percent_online', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis.ciudadmodel')),
            ],
            options={
                'ordering': ['denominacion'],
            },
        ),
    ]
