# Generated by Django 4.0.6 on 2022-08-31 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodo',
            options={'ordering': ['denominacion'], 'verbose_name': 'Nodo', 'verbose_name_plural': 'Nodos'},
        ),
        migrations.AlterModelTable(
            name='nodo',
            table='red_nodo',
        ),
    ]
