# Generated by Django 4.0.6 on 2022-09-01 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CablemodemCountMonitoredModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_monitoring', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Cablemodem Monitoreado',
                'verbose_name_plural': 'Cablemodems Monitoreados',
                'db_table': 'metrics_monitoreo_cablemodem',
            },
        ),
        migrations.CreateModel(
            name='CuadrillaTecnicaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='nombre')),
                ('alias', models.CharField(max_length=15, unique=True, verbose_name='abreviación')),
                ('work_phone', models.CharField(blank=True, max_length=13, verbose_name='numero telefónico')),
                ('is_in_service', models.BooleanField(default=True, verbose_name='en servicio')),
            ],
            options={
                'verbose_name': 'Cuadrilla Tecnica',
                'verbose_name_plural': 'Cuadrillas Tecnicas',
                'db_table': 'metrics_cuadrilla_tecnica',
            },
        ),
        migrations.CreateModel(
            name='EmpresaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25, unique=True, verbose_name='empresa')),
                ('boss_name', models.CharField(max_length=50, verbose_name='encargado')),
                ('work_phone', models.CharField(max_length=13, verbose_name='telefono del encargado')),
                ('is_in_service', models.BooleanField(default=True, verbose_name='en servicio')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'metrics_empresa',
            },
        ),
        migrations.CreateModel(
            name='LlamadasTecnicasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.PositiveSmallIntegerField()),
                ('fecha', models.DateField()),
                ('fecha_detalle', models.DateTimeField(blank=True, max_length=100)),
                ('origen_src', models.CharField(blank=True, max_length=100)),
                ('destino_dst', models.CharField(blank=True, max_length=100)),
                ('canal_channel', models.CharField(blank=True, max_length=100)),
                ('canal_destino_dstchannel', models.CharField(blank=True, max_length=100)),
                ('estado_disposition', models.CharField(blank=True, max_length=100)),
                ('id_unico', models.CharField(blank=True, max_length=100)),
                ('grabacion', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Llamadas Tecnicas',
                'db_table': 'metrics_llamada_tecnica',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='NodoEventoEquipoAfectadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.PositiveBigIntegerField()),
                ('macaddress', models.CharField(max_length=12)),
                ('model', models.CharField(max_length=50)),
                ('cuenta', models.PositiveBigIntegerField()),
                ('domicilio', models.CharField(max_length=50)),
                ('estado_provisioning', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('online_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detalle Evento de Nodo',
                'verbose_name_plural': 'Detalle Evento de Nodo',
                'db_table': 'metrics_nodo_detalle_evento',
            },
        ),
        migrations.CreateModel(
            name='NodoEventoModel',
            fields=[
                ('eventid', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('nodo', models.CharField(max_length=50)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('antiguedad', models.CharField(max_length=50)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('duracion', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('equipos_afectados', models.PositiveSmallIntegerField()),
                ('equipos_caidos', models.PositiveSmallIntegerField()),
                ('porcentaje_online', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Evento de Nodo',
                'verbose_name_plural': 'Eventos de Nodos',
                'db_table': 'metrics_nodo_evento',
            },
        ),
        migrations.CreateModel(
            name='ReclamosCompletedWorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='terminados')),
                ('technical_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metrics.cuadrillatecnicamodel', verbose_name='cuadrilla')),
            ],
            options={
                'verbose_name': 'Reclamo Realizado',
                'verbose_name_plural': 'Reclamos Realizado',
                'db_table': 'metrics_reclamos_completedworks',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='cuadrillatecnicamodel',
            name='company_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metrics.empresamodel', verbose_name='empresa'),
        ),
        migrations.CreateModel(
            name='ConexionesCompletedWorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='terminados')),
                ('technical_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metrics.cuadrillatecnicamodel', verbose_name='cuadrilla')),
            ],
            options={
                'verbose_name': 'Conexion Realizada',
                'verbose_name_plural': 'Conexiones Realizadas',
                'db_table': 'metrics_conexiones_completedworks',
                'ordering': ['-date'],
            },
        ),
    ]
