# Generated by Django 4.0.6 on 2022-09-01 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cuadrillatecnicamodel',
            table='common_cuadrilla_tecnica',
        ),
        migrations.AlterModelTable(
            name='empresamodel',
            table='common_empresa',
        ),
    ]
