# Generated by Django 4.0.6 on 2022-09-07 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_remove_nodoeventoequipoafectadomodel_eventid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodoeventoequipoafectadomodel',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afectados', to='metrics.nodoeventomodel'),
        ),
        migrations.AlterField(
            model_name='nodoeventomodel',
            name='antiguedad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
