# Generated by Django 4.0.6 on 2022-09-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_alter_nodoeventoequipoafectadomodel_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodoeventomodel',
            name='duracion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
